library(shiny)
library(shinythemes)
library(shinyWidgets)
library(DEP)
library(shinydashboard)
library(gplots)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(ggpubr)
library(tidyverse)
library(viridis)
library(readr)
library(ggrepel)
library(DOSE)
library(enrichplot)
library(org.Hs.eg.db) # genome wide association human
library(org.Mm.eg.db) #genome wide association mouse
library(clusterProfiler)
library(ggridges)
library(pathview)
library(profileR)
library(corrplot)
library(DT)
library(patchwork)
library(pcaMethods)
library(heatmaply)
library(ggnewscale)
library(rhandsontable)
library(limma)
library(SummarizedExperiment)
library(colourpicker)
library(shinycssloaders)

