---
title: "report.Rmd"
output: pdf_document
params:
    experimentDesign: NA
    contaminants: NA
    missingValues: NA
    normalization: NA
    imputation: NA
    scatter: NA
    correlation: NA
    PCA: NA
    heatMap: NA
    heatMapTopContributors: NA
    heatMap2: NA
    volcano: NA
    profile: NA
    geneOntology: NA
    GSEAenrichment: NA
    networkEnrichment: NA
    diseaseaseEnrinchment: NA
    diseaseaseGSEA: NA
    diseaseaseHeatmap: NA
    diseaseaseDensity: NA
    diseaseaseAssociation: NA
    diseaseaseCircus: NA
    diseaseaseNetwork: NA
    diseaseaseMap: NA
    pathway: NA
    interactions: NA
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F)
```

## Proteomics Report



## Experiment design

```{r expdesign}

if (!is.null(params$experimentDesign)) {

     kableExtra::kbl(params$experimentDesign, align = 'c') 
}

```

```{r contaminants, fig.width=10, fig.height=12}
if (!is.null(params$contaminants)) {

    print(params$contaminants)
}

```

```{r missvalues,fig.width=10, fig.height=12}
if (!is.null(params$missingValues)) {

    print(params$missingValues)
}
```

```{r normalization,fig.width=10, fig.height=12}
if (!is.null(params$normalization)) {

    print(params$normalization)
}
```

```{r imputation,fig.width=10, fig.height=12}
if (!is.null(params$imputation)) {

    print(params$imputation)
}
```

```{r scatter,fig.width=10, fig.height=12}

if (!is.null(params$scatter)) {

    print(params$scatter)        
}
```

```{r correlation,fig.width=10, fig.height=12}

if (!is.null(params$correlation)) {

    MQanalyser::plot_correlationly(params$correlation, interactive = F) 
    
}
```

```{r PCA,fig.width=10, fig.height=12}

if (!is.null(params$PCA)) {

    print(params$PCA)            
}
```

```{r heatmap, echo = FALSE,fig.width=10, fig.height=12}

if (!is.null(params$heatMap)) {

    if (params$heatMapTopContributors == TRUE) {

        MQanalyser::plot_heatmaply(dep = params$heatMap$dep,
                       intensity_type = params$heatMap$IntensityType,
                       top_contributors = params$heatMap$topContributors,
                       interactive = FALSE)
    }else{
        print(params$heatMap)
    }
}
```

```{r heatmap2,fig.width=10, fig.height=12}

if (!is.null(params$heatmap2)) {

    print(params$heatmap2)            
}
```

```{r volcano,fig.width=10, fig.height=12}

if (!is.null(params$volcano)) {

    print(params$volcano)            
}
```

```{r profile,fig.width=10, fig.height=12}

if (!is.null(params$profile)) {

    print(params$profile)            
}
```

```{r geneOntology,fig.width=10, fig.height=12}

if (!is.null(params$geneOntology)) {

    print(params$geneOntology)            
}
```

```{r GSEAenrichment,fig.width=10, fig.height=12}

if (!is.null(params$GSEAenrichment)) {

    print(params$GSEAenrichment)            
}
```

```{r networkEnrichment,fig.width=10, fig.height=12}

if (!is.null(params$networkEnrichment)) {

    print(params$networkEnrichment)            
}
```

```{r diseaseaseEnrinchment,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseEnrinchment)) {

    print(params$diseaseaseEnrinchment)            
}
```

```{r diseaseaseGSEA,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseGSEA)) {

    print(params$diseaseaseGSEA)            
}
```

```{r diseaseaseHeatmap,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseHeatmap)) {

    print(params$diseaseaseHeatmap)            
}
```


```{r diseaseaseDensity,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseDensity)) {

    print(params$diseaseaseDensity)            
}
```


```{r diseaseaseAssociation,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseAssociation)) {

    print(params$diseaseaseAssociation)            
}
```

```{r diseaseaseCircus,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseCircus)) {

    print(params$diseaseaseCircus)            
}
```

```{r diseaseaseNetwork,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseNetwork)) {

    print(params$diseaseaseNetwork)            
}
```

```{r diseaseaseMap,fig.width=10, fig.height=12}

if (!is.null(params$diseaseaseMap)) {

    print(params$diseaseaseMap)            
}
```

```{r pathway,fig.width=10, fig.height=12}

if (!is.null(params$pathway)) {

    print(params$pathway)            
}
```


```{r interactions,fig.width=10, fig.height=12, echo = FALSE,results='hide',fig.keep='all'}

if (!is.null(params$interactions)) {

    string_db <- STRINGdb$new(version = "11.5", species=9606,
                               score_threshold = 200, input_directory="")
    
    print(string_db$plot_network(params$interactions))            
}
```




